apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: clair-postgres-deployment
  name: clair-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: clair-postgres-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: clair-postgres-deployment
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        image: arminc/clair-db:latest
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
