apiVersion: v1
kind: Service
metadata:
  labels:
    run: clair-postgres-service
  name: clair-postgres-service
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30609
  selector:
    run: clair-postgres-deployment
