apiVersion: v1
kind: Service
metadata:
  labels:
    run: portauthority-postgres-service
  name: portauthority-postgres-service
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30607
  selector:
    run: portauthority-postgres-deployment
